import type { Metadata } from "next";
import {  Sora } from "next/font/google";
import "./globals.css";


const sora = Sora({
  weight: ["400", "600", "700"],
  variable: "--font-sora",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
